"use client";

import Image from "next/image";
import type { PredictionResult } from "@/types/prediction";
import { PREDICTION_SEVERITY, SEVERITY_STYLES } from "@/utils/constants";
import AnimatedReveal from "@/components/common/AnimatedReveal";
import Confetti from "@/components/common/Confetti";

interface ResultCardProps {
  result: PredictionResult;
  onReset: () => void;
}

function escapeHtml(text: string | number): string {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export default function ResultCard({ result, onReset }: ResultCardProps) {
  const severity = PREDICTION_SEVERITY[result.prediction] ?? "moderate";
  const styles = SEVERITY_STYLES[severity];
  const isPositive = severity === "high";

  const handleExport = () => {
    const now = new Date();
    const iso = now.toISOString();
    const readable = now.toLocaleString();
    const filename = `depression-report-${iso.replace(/[:.]/g, "-")}.html`;

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Depression Detection Report — ${readable}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; background: #f8fafc; color: #0f172a; margin: 0; padding: 40px 20px; }
  .page { max-width: 720px; margin: 0 auto; background: #fff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 40px rgba(0,0,0,0.08); }
  .accent { height: 6px; background: linear-gradient(90deg, #22c55e, #10b981); }
  .body { padding: 40px; }
  h1 { margin: 0 0 4px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.1em; color: #64748b; }
  h2 { margin: 0 0 24px; font-size: 22px; color: #0f172a; font-weight: 700; }
  .chip { display: inline-block; padding: 6px 14px; border-radius: 999px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; background: ${isPositive ? "#fee2e2" : "#dcfce7"}; color: ${isPositive ? "#b91c1c" : "#15803d"}; margin-bottom: 20px; }
  .result { font-size: 36px; font-weight: 800; color: ${isPositive ? "#dc2626" : "#16a34a"}; margin: 0 0 8px; }
  .message { font-size: 15px; color: #475569; line-height: 1.6; margin: 0 0 32px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 32px; }
  .stat { padding: 18px; background: #f1f5f9; border-radius: 10px; }
  .stat-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #64748b; margin-bottom: 6px; }
  .stat-value { font-size: 22px; font-weight: 700; color: #0f172a; font-variant-numeric: tabular-nums; }
  .meta { font-size: 12px; color: #64748b; margin-bottom: 24px; padding-top: 16px; border-top: 1px solid #e2e8f0; }
  .meta-row { display: flex; justify-content: space-between; padding: 4px 0; }
  .disclaimer { margin-top: 24px; padding: 14px 16px; background: #fef3c7; border: 1px solid #fde68a; border-radius: 8px; font-size: 12px; color: #78350f; line-height: 1.5; }
  footer { padding: 16px 40px; background: #f8fafc; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
  @media print { body { background: #fff; padding: 0; } .page { box-shadow: none; border-radius: 0; } }
</style>
</head>
<body>
  <div class="page">
    <div class="accent"></div>
    <div class="body">
      <h1>Prediction Report</h1>
      <h2>Multimodal Depression Detection System</h2>

      <div class="chip">Prediction Result</div>
      <p class="result">${escapeHtml(result.prediction)}</p>
      <p class="message">${escapeHtml(result.message)}</p>

      <div class="meta">
        <div class="meta-row"><span>Report generated</span><span>${escapeHtml(readable)}</span></div>
        <div class="meta-row"><span>Model</span><span>D-Vlog cross-modal attention</span></div>
      </div>

      <div class="disclaimer">
        <strong>Disclaimer:</strong> This report is generated by a research model
        and is <strong>not a medical diagnosis</strong>. Please consult a qualified
        healthcare professional for clinical evaluation.
      </div>
    </div>
    <footer>Multimodal Depression Detection System · Research &amp; educational demo</footer>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <AnimatedReveal direction="zoom" duration={800}>
      <Confetti fire={!isPositive} />
      <div className="card-static relative overflow-hidden">
        <div
          className={`pointer-events-none absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${styles.gradient}`}
        />

        <div className="flex flex-col items-center gap-5 text-center">
          <span
            className={`inline-flex items-center gap-2 rounded-full border ${styles.border} ${styles.bg} ${styles.text} px-3 py-1 text-xs font-semibold uppercase tracking-wider`}
          >
            <span className={`h-2 w-2 rounded-full ${styles.dot}`} />
            Prediction Result
          </span>

          <div
            className={`relative grid h-20 w-20 place-items-center overflow-hidden rounded-full bg-gradient-to-br ${styles.gradient} p-0.5 shadow-lg ring-2 ring-white/10`}
          >
            <div className="grid h-full w-full place-items-center overflow-hidden rounded-full bg-surface-2">
              <Image
                src={isPositive ? "/gif/sad.gif" : "/gif/smile.gif"}
                alt={isPositive ? "Sad face" : "Smiling face"}
                width={80}
                height={80}
                unoptimized
                className="h-full w-full object-cover"
              />
            </div>
          </div>

          <h3 className="text-3xl font-bold text-ink sm:text-4xl">
            {result.prediction}
          </h3>

          <p className="max-w-md text-sm text-muted">{result.message}</p>
        </div>

        <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center">
          <button type="button" onClick={onReset} className="btn-primary">
            Run Another Prediction
          </button>
          <button
            type="button"
            onClick={handleExport}
            className="btn-outline"
          >
            Export Report
          </button>
        </div>

        <p className="mt-6 rounded-lg border border-yellow-500/30 bg-yellow-500/10 p-3 text-xs text-yellow-300">
          <strong>Disclaimer:</strong> This result is generated by a research model
          and is not a medical diagnosis. Please consult a qualified healthcare
          professional for clinical evaluation.
        </p>
      </div>
    </AnimatedReveal>
  );
}
