"use client";

import Image from "next/image";
import type { PredictionResult } from "@/types/prediction";
import { PREDICTION_SEVERITY, SEVERITY_STYLES } from "@/utils/constants";
import AnimatedReveal from "@/components/common/AnimatedReveal";

interface ResultCardProps {
  result: PredictionResult;
  onReset: () => void;
}

export default function ResultCard({ result, onReset }: ResultCardProps) {
  const severity = PREDICTION_SEVERITY[result.prediction] ?? "moderate";
  const styles = SEVERITY_STYLES[severity];
  const isPositive = severity === "high";

  return (
    <AnimatedReveal direction="zoom" duration={800}>
      <div className="card-static relative overflow-hidden">
        <div
          className={`pointer-events-none absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${styles.gradient}`}
        />

        <div className="flex flex-col items-center gap-5 text-center">
          <span
            className={`inline-flex items-center gap-2 rounded-full border ${styles.border} ${styles.bg} ${styles.text} px-3 py-1 text-xs font-semibold uppercase tracking-wider`}
          >
            <span className={`h-2 w-2 rounded-full ${styles.dot}`} />
            Prediction Result
          </span>

          <div
            className={`relative grid h-20 w-20 place-items-center overflow-hidden rounded-full bg-gradient-to-br ${styles.gradient} p-0.5 shadow-lg ring-2 ring-white/10`}
          >
            <div className="grid h-full w-full place-items-center overflow-hidden rounded-full bg-surface-2">
              <Image
                src={isPositive ? "/gif/sad.gif" : "/gif/smile.gif"}
                alt={isPositive ? "Sad face" : "Smiling face"}
                width={80}
                height={80}
                unoptimized
                className="h-full w-full object-cover"
              />
            </div>
          </div>

          <h3 className="text-3xl font-bold text-ink sm:text-4xl">
            {result.prediction}
          </h3>

          <p className="max-w-md text-sm text-muted">{result.message}</p>
        </div>

        <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center">
          <button type="button" onClick={onReset} className="btn-primary">
            Run Another Prediction
          </button>
          <button
            type="button"
            onClick={() => window.print()}
            className="btn-outline"
          >
            Export Report
          </button>
        </div>

        <p className="mt-6 rounded-lg border border-yellow-500/30 bg-yellow-500/10 p-3 text-xs text-yellow-300">
          <strong>Disclaimer:</strong> This result is generated by a research model
          and is not a medical diagnosis. Please consult a qualified healthcare
          professional for clinical evaluation.
        </p>
      </div>
    </AnimatedReveal>
  );
}
