import type { PredictionResult } from "@/types/prediction";
import { PREDICTION_SEVERITY, SEVERITY_STYLES } from "@/utils/constants";

interface ResultCardProps {
  result: PredictionResult;
  onReset: () => void;
}

export default function ResultCard({ result, onReset }: ResultCardProps) {
  const severity = PREDICTION_SEVERITY[result.prediction] ?? "moderate";
  const styles = SEVERITY_STYLES[severity];
  const isPositive = severity === "high";

  return (
    <div className="card-static animate-fade-up relative overflow-hidden">
      <div
        className={`pointer-events-none absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${styles.gradient}`}
      />

      <div className="flex flex-col items-center gap-5 text-center">
        <span
          className={`inline-flex items-center gap-2 rounded-full border ${styles.border} ${styles.bg} ${styles.text} px-3 py-1 text-xs font-semibold uppercase tracking-wider`}
        >
          <span className={`h-2 w-2 rounded-full ${styles.dot}`} />
          Prediction Result
        </span>

        <div
          className={`grid h-20 w-20 place-items-center rounded-full bg-gradient-to-br ${styles.gradient} text-black shadow-lg`}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2.4"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="h-10 w-10"
          >
            {isPositive ? (
              <>
                <circle cx="12" cy="12" r="10" />
                <line x1="12" y1="8" x2="12" y2="12" />
                <line x1="12" y1="16" x2="12.01" y2="16" />
              </>
            ) : (
              <>
                <circle cx="12" cy="12" r="10" />
                <path d="m9 12 2 2 4-4" />
              </>
            )}
          </svg>
        </div>

        <h3 className="text-3xl font-bold text-ink sm:text-4xl">
          {result.prediction}
        </h3>

        <p className="max-w-md text-sm text-muted">{result.message}</p>
      </div>

      <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center">
        <button type="button" onClick={onReset} className="btn-primary">
          Run Another Prediction
        </button>
        <button
          type="button"
          onClick={() => window.print()}
          className="btn-outline"
        >
          Export Report
        </button>
      </div>

      <p className="mt-6 rounded-lg border border-yellow-500/30 bg-yellow-500/10 p-3 text-xs text-yellow-300">
        <strong>Disclaimer:</strong> This result is generated by a research model
        and is not a medical diagnosis. Please consult a qualified healthcare
        professional for clinical evaluation.
      </p>
    </div>
  );
}
